name: tiwao-api
services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
      target: dev
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    depends_on:
      - mongodb
      - redis
    environment:
      - DATABASE_URL=mongodb://tiwao:password@mongodb:27017/tiwao_db?retryWrites=true&w=majority
      - KV_URL=redis://:redis_password@redis:6379
    # network_mode: service:db
    networks:
      - app

  # Not suitable as Prisma has a hard requirement for MongoDB to exist as a replica set
  # mongodb:
  #   image: mongodb/mongodb-community-server:7.0.8-ubi8
  #   container_name: mongodb
  #   hostname: mongodb
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app
  #   volumes:
  #     - mongodb-data:/data/db
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    hostname: mongodb
    volumes:
      - mongodb-data:/bitnami/mongodb:rw
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGODB_ROOT_PASSWORD=root_password
      - MONGODB_USERNAME=tiwao
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=tiwao_db
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  db-secondary:
    container_name: db-secondary
    depends_on:
      - mongodb
    environment:
        - MONGODB_REPLICA_SET_MODE=secondary
        - MONGODB_ADVERTISED_HOSTNAME=db-secondary # omit if scalling
        - MONGODB_INITIAL_PRIMARY_HOST=mongodb
        - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
        - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root_password
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
    image: bitnami/mongodb:latest
  
  db-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root_password
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
  
  redis:
    image: redis:latest
    hostname: redis
    command: redis-server --save 60 1 --loglevel warning --requirepass redis_password
    ports:
      - 6379:6379
    networks:
      - app

volumes:
  mongodb-data:

networks:
  app:
    driver: bridge
